export const REQUEST_METADATA = 'REQUEST_METADATA';
export const RECEIVE_METADATA_SUCCESS = 'RECEIVE_METADATA_SUCCESS';
export const RECEIVE_METADATA_ERROR = 'RECEIVE_METADATA_ERROR';
export const CLEAR_METADATA_ERROR = 'CLEAR_METADATA_ERROR';
