export const REQUEST_USER = 'REQUEST_USER';
export const RECEIVE_USER_SUCCESS = 'RECEIVE_USER_SUCCESS';
export const RECEIVE_USER_ERROR = 'RECEIVE_USER_ERROR';
export const CLEAR_USER_ERROR = 'CLEAR_USER_ERROR';
