export const SELECT_FIELD = 'SELECT_FIELD';
export const DESELECT_FIELD = 'DESELECT_FIELD';
export const SELECT_RELATIONSHIP = 'SELECT_RELATIONSHIP';
export const DESELECT_RELATIONSHIP = 'DESELECT_RELATIONSHIP';
