export const SELECT_SOBJECT = 'SELECT_SOBJECT';
export const DESELECT_SOBJECT = 'DESELECT_SOBJECT';
export const TOGGLE_FIELD = 'TOGGLE_FIELD';
export const TOGGLE_RELATIONSHIP = 'TOGGLE_RELATIONSHIP';
export const UPDATE_SOQL = 'UPDATE_SOQL';
