export const REQUEST_SOBJECTS = 'REQUEST_SOBJECTS';
export const RECEIVE_SOBJECTS_SUCCESS = 'RECEIVE_SOBJECTS_SUCCESS';
export const RECEIVE_SOBJECTS_ERROR = 'RECEIVE_SOBJECTS_ERROR';
export const SELECT_SOBJECT = 'SELECT_SOBJECT';
export const DESELECT_SOBJECT = 'DESELECT_SOBJECT';
