export const REQUEST_API = 'REQUEST_API';
export const RECEIVE_API_SUCCESS = 'RECEIVE_API_SUCCESS';
export const RECEIVE_API_ERROR = 'RECEIVE_API_ERROR';
export const CLEAR_API_ERROR = 'CLEAR_API_ERROR';
