export const REQUEST_QUERY = 'REQUEST_QUERY';
export const RECEIVE_QUERY_SUCCESS = 'RECEIVE_QUERY_SUCCESS';
export const RECEIVE_QUERY_ERROR = 'RECEIVE_QUERY_ERROR';
export const CLEAR_QUERY_ERROR = 'CLEAR_QUERY_ERROR';
